--------------------------------------------------------
--  File created - Wednesday-July-05-2023   
--------------------------------------------------------
-- Unable to render TABLE DDL for object THUCTAP.KEHOACH with DBMS_METADATA attempting internal generator.
ALTER TABLE KEHOACH
ADD CONSTRAINT KEHOACH_FK1 FOREIGN KEY
(
  DV_ID 
)
REFERENCES DONVI
(
  DV_ID 
)
ENABLE
ALTER TABLE KEHOACH
ADD CONSTRAINT KEHOACH_FK2 FOREIGN KEY
(
  NV_ID 
)
REFERENCES NHANVIEN
(
  NV_ID 
)
ENABLECREATE TABLE KEHOACH 
(
  KH_ID NUMBER NOT NULL 
, KH_TEN VARCHAR2(255 BYTE) 
, KH_STT VARCHAR2(20 BYTE) 
, KH_LOAIKEHOACH VARCHAR2(30 BYTE) 
, KH_THGIANBATDAU DATE 
, KH_THGIANKETTHUC DATE 
, KH_TONGTHGIAN NUMBER DEFAULT 0 
, DV_ID NUMBER 
, NV_ID NUMBER 
, KH_TRANGTHAI NUMBER DEFAULT 0 
, CONSTRAINT KEHOACH_PK PRIMARY KEY 
  (
    KH_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX KEHOACH_PK ON KEHOACH (KH_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
REM INSERTING into THUCTAP.KEHOACH
SET DEFINE OFF;
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (6,'K? ho?ch quý 1','12','K? Ho?ch Quý',to_date('01-JUL-23','DD-MON-RR'),to_date('31-JUL-23','DD-MON-RR'),3000,4,7,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (10,'K? Ho?ch Tháng 1','1','K? Ho?ch Tháng',to_date('01-JAN-23','DD-MON-RR'),to_date('31-JAN-23','DD-MON-RR'),100,4,7,5);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (7,'K? ho?ch tháng 5','12','K? Ho?ch Tháng',to_date('01-JUL-23','DD-MON-RR'),to_date('31-JUL-23','DD-MON-RR'),3456,3,7,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (11,'K? Ho?ch Tháng 2','13','K? Ho?ch Tháng',to_date('01-FEB-23','DD-MON-RR'),to_date('28-FEB-23','DD-MON-RR'),null,3,4,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (12,'K? Ho?ch Tháng 3','12','K? Ho?ch Tháng',to_date('01-MAR-23','DD-MON-RR'),to_date('31-MAR-23','DD-MON-RR'),null,3,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (13,'K? Ho?ch Tháng 4','12','K? Ho?ch Tháng',to_date('01-APR-23','DD-MON-RR'),to_date('30-APR-23','DD-MON-RR'),null,2,1,3);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (14,'K? Ho?ch Tháng 5','12','K? Ho?ch Tháng',to_date('01-MAY-23','DD-MON-RR'),to_date('31-MAY-23','DD-MON-RR'),null,2,1,4);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (15,'K? Ho?ch Tháng 10','20','K? Ho?ch Tháng',to_date('01-OCT-23','DD-MON-RR'),to_date('31-OCT-23','DD-MON-RR'),null,3,1,5);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (16,'K? Ho?ch Tháng 11','15','K? Ho?ch Tháng',to_date('01-NOV-23','DD-MON-RR'),to_date('30-NOV-23','DD-MON-RR'),null,3,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (17,'K? Ho?ch Tháng 12','16','K? Ho?ch Tháng',to_date('01-DEC-23','DD-MON-RR'),to_date('31-DEC-23','DD-MON-RR'),null,2,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (30,'K? Ho?ch Tháng 7','1','K? Ho?ch Tháng',to_date('01-JUL-23','DD-MON-RR'),to_date('31-JUL-23','DD-MON-RR'),0,4,7,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (27,'K? ho?ch tháng 8','1','K? Ho?ch Tháng',to_date('01-AUG-23','DD-MON-RR'),to_date('31-AUG-23','DD-MON-RR'),0,4,7,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (23,'K? ho?ch Quý 2','1','K? Ho?ch Quý',to_date('03-JUL-23','DD-MON-RR'),to_date('12-JUL-23','DD-MON-RR'),0,7,4,0);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (1,'K? ho?ch ??t xu?t','1','K? ho?ch ??t xu?t',to_date('01-JAN-23','DD-MON-RR'),to_date('31-DEC-23','DD-MON-RR'),365,3,1,3);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (2,'Xây d?ng web qu?n lí nhân viên','2','K? Ho?ch Quý',to_date('01-JAN-23','DD-MON-RR'),to_date('31-DEC-23','DD-MON-RR'),365,4,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (18,'K? Ho?ch Tháng 7','1','K? Ho?ch Tháng',to_date('28-JUN-23','DD-MON-RR'),to_date('30-JUN-23','DD-MON-RR'),0,4,7,1);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (4,'Xây d?ng web qu?n lí báo cáo','4','K? Ho?ch Tháng',to_date('01-JUN-23','DD-MON-RR'),to_date('30-JUN-23','DD-MON-RR'),200,2,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (8,'K? ho?ch 8','8','K? Ho?ch Tháng',to_date('01-AUG-23','DD-MON-RR'),to_date('31-AUG-23','DD-MON-RR'),5,7,1,2);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (5,'Th?c t?p 2023','1','K? Ho?ch Tháng',to_date('01-MAY-23','DD-MON-RR'),to_date('31-MAY-23','DD-MON-RR'),300,3,1,1);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (9,'K? ho?ch 9','9','K? Ho?ch Tháng',to_date('01-SEP-23','DD-MON-RR'),to_date('30-SEP-23','DD-MON-RR'),5,3,1,3);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (20,'K? ho?ch tháng 6','1','K? Ho?ch Tháng',to_date('03-JUL-23','DD-MON-RR'),to_date('13-JUL-23','DD-MON-RR'),0,4,7,5);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (29,'test1','1','K? Ho?ch Tháng',to_date('04-JUL-23','DD-MON-RR'),to_date('31-AUG-23','DD-MON-RR'),0,4,7,0);
Insert into THUCTAP.KEHOACH (KH_ID,KH_TEN,KH_STT,KH_LOAIKEHOACH,KH_THGIANBATDAU,KH_THGIANKETTHUC,KH_TONGTHGIAN,DV_ID,NV_ID,KH_TRANGTHAI) values (28,'K? ho?ch tháng 7','1','K? Ho?ch Tháng',to_date('01-JUL-23','DD-MON-RR'),to_date('31-JUL-23','DD-MON-RR'),0,4,7,2);
-- Unable to render TRIGGER DDL for object THUCTAP.KEHOACH_TRG with DBMS_METADATA attempting internal generator.
CREATE TRIGGER KEHOACH_TRG 
BEFORE INSERT ON KEHOACH 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
-- Unable to render TRIGGER DDL for object THUCTAP.KEHOACH_TRG1 with DBMS_METADATA attempting internal generator.
CREATE TRIGGER KEHOACH_TRG1 
BEFORE INSERT ON KEHOACH 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
