--------------------------------------------------------
--  File created - Wednesday-July-05-2023   
--------------------------------------------------------
-- Unable to render TABLE DDL for object THUCTAP.XINGIAHAN with DBMS_METADATA attempting internal generator.
COMMENT ON COLUMN XINGIAHAN.NV_IDDUYET IS 'ng??i duy?t ??n';
COMMENT ON COLUMN XINGIAHAN.NV_ID IS 'ng??i xin gia ha?n';ALTER TABLE XINGIAHAN
ADD CONSTRAINT XINGIAHAN_FK1 FOREIGN KEY
(
  NV_ID 
)
REFERENCES NHANVIEN
(
  NV_ID 
)
ENABLE
ALTER TABLE XINGIAHAN
ADD CONSTRAINT XINGIAHAN_FK2 FOREIGN KEY
(
  NV_IDDUYET 
)
REFERENCES NHANVIEN
(
  NV_ID 
)
ON DELETE SET NULL ENABLE
ALTER TABLE XINGIAHAN
ADD CONSTRAINT XINGIAHAN_FK3 FOREIGN KEY
(
  CV_ID 
)
REFERENCES CONGVIEC
(
  CV_ID 
)
ENABLECREATE TABLE XINGIAHAN 
(
  HG_ID NUMBER NOT NULL 
, HG_LIDO VARCHAR2(20 BYTE) 
, HG_THGIANDENGHI DATE 
, NV_IDDUYET NUMBER 
, NV_ID NUMBER 
, CV_ID NUMBER 
, HG_TRANGTHAI NUMBER DEFAULT 0 
, CONSTRAINT XINGIAHAN_PK PRIMARY KEY 
  (
    HG_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XINGIAHAN_PK ON XINGIAHAN (HG_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
REM INSERTING into THUCTAP.XINGIAHAN
SET DEFINE OFF;
